POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "Type wars",
  "author": "Robert C. Martin",
  "url": "http://blog.cleancoder.com/uncle-bob/2016/05/01/TypeWars.html",
  "likes": "2"
}

###

POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "Type wars 2",
  "author": "Robert C. Martin",
  "url": "http://blog.cleancoder.com/uncle-bob/2016/05/01/TypeWars.html",
  "likes": "9"
}

###

POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "Type wars 3",
  "author": "Robert C. Martin",
  "url": "http://blog.cleancoder.com/uncle-bob/2016/05/01/TypeWars.html",
  "likes": "34"
}